---
image: python:3-slim
stages:
  - validate
setup:
  stage: .pre
  script:
    - pip install -r requirements.txt
  tags:
    - docker
validate:
  stage: validate
  script:
    - ansible-lint .
  tags:
    - docker
