---
image: python:3-slim
stages:
  - lint
lint:
  stage: lint
  script:
    - apt-get update -y && apt-get install -y git --no-install-recommends
    - pip install -r requirements.txt
    - cd "$CI_PROJECT_DIR/deploy"
    - ansible-galaxy install -r requirements.yml
    - ansible-lint -c .ansible-lint
  tags:
    - docker
