---
image: python:3-slim
stages:
  - lint
lint:
  stage: lint
  script:
    - pip install -r requirements.txt
    - ansible-lint "$CI_PROJECT_DIR/deploy" -c "${CI_PROJECT_DIR}/deploy/.ansible-lint"
  tags:
    - docker
