---
image: python:3-slim
stages:
  - lint
lint:
  stage: lint
  script:
    - pip install -r requirements.txt
    - ansible-lint . \
      --exclude .devcontainer/docker-compose.yml \
      --exclude .gitlab-ci.yml \
      --exclude .markdownlint.yaml \
      --exclude .pre-commit-config.yml
  tags:
    - docker
