---
image: python:3-slim
stages:
- lint
lint:
  stage: lint
  script:
  - apt update -y && apt install -y git
  - pip install -r requirements.txt
  - cd "$CI_PROJECT_DIR/deploy"
  - ansible-galaxy install -r requirements.yml
  - ansible-lint -c .ansible-lint
  tags:
  - docker
