---
enable_stack: true
gitlab_stack: enabled

print_facts: false

arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"

cfssl_services:
  - gitlab
  - traefik
cfssl_ca:
  CN: "{{ certificate_cn }}"
  key:
    algo: rsa
    size: 4096
  names:
    - C: "{{ cfssl_ca_country | default('US') }}"
      ST: "{{ cfssl_ca_state | default('UT') }}"
      L: "{{ cfssl_ca_location | default('Salt Lake City') }}"
      O: "{{ cfssl_ca_org | default('DevOps') }}"
cfssl_config:
  signing:
    default:
      expiry: 8760h
    profiles:
      client:
        usages:
          - signing
          - digital signature
          - key encipherment
          - client auth
        expiry: 8760h
      server:
        usages:
          - signing
          - digital signature
          - key encipherment
          - server auth
        expiry: 8760h

compose_directory: /dkr
compose_project_name: gitlab
compose_user: gitlab
container_tags:
  - name: cfssl
    tag: v1.6.5
  - name: gitlab
    tag: 18.1.1-ce.0
  - name: postgres
    tag: 16.9-alpine
  - name: redis
    tag: 8.0.2-alpine
  - name: traefik
    tag: v3.4.3

docker_network:
  enable_ipv6: false
  subnet:
    ipv4: 172.20.0.0/24
    ipv6: fd00:1101:1001:10::/64
  traefik:
    ports:
      - source: 22
      - source: 80
      - source: 443
docker_users:
  - "{{ compose_user }}"

# domain: example.net

gitlab:
  ssh_port: 2222
  enable_registry: true
  enable_localhost: true
  env:
    DB_USER: postgres
    DB_PASS: postgres
    DB_NAME: gitlab
    GITLAB_HOST: gitlab.${DOMAIN}
    # GITLAB_ROOT_PASSWORD: ${GITLAB_ROOT_PASSWORD}
    GITLAB_TIMEZONE: America/Denver

htpasswd_credentials:
  - path: "{{ traefik_directory_result.path }}/usersfile"
    owner: "{{ compose_user }}"
    group: "{{ compose_user }}"
    mode: "0644"
    users:
      - username: traefik
        password: "{{ traefik_htpasswd | default('traefik') }}"
        crypt_scheme: apr_md5_crypt

upstream_dns:
  - 1.1.1.3
  - 1.0.0.3

users:
  - username: gitlab
    comment: GitLab
    shell: /bin/bash
    exclusive_ssh_key: true
    # ssh_key: "{{ ssh_pub_key }}"
    use_sudo: true
    use_sudo_nopass: true
    user_state: present
    servers:
      - all

traefik:
  enable_dashboard: false
  enable_htpasswd: false
  enable_metrics: false
  use_letsencrypt: false
